name: 部署博客到 GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: 安装依赖
        run: pnpm install

      - name: 设置 Pages
        uses: actions/configure-pages@v5

      - name: 生成静态文件
        run: pnpm run build

      - name: 上传到Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4